### ISSUE TITLE
 how to configure HTTP headers on request.

### ISSUE THREAD

**Issue by arden** [s4cha/ws#10]
how to configure HTTP headers on request?

**Comment by adolfo** [comment]
@arden I was looking into this as well. Did you find a solution? It looks like the methods that could be subclassed and overwritten are marked internal/private.

Something along the lines of `public var headers: [String: String]`on `WS` or `WSCall` would be great.

**Comment by s4cha** [comment]
This is now available in version 1.2.1 kudos to @adolfo 👏!!
