### ISSUE TITLE
Is it possible to handle all the error before calling next block?

### ISSUE THREAD

**Issue by yuhua-chen** [s4cha/ws#13]
The situation is I want to take care of the auth error if the API token is expired for each request. It's like Aspect pattern to hijack all the error response and handle the auth in a same place. Any suggestions would be helpful. Thank you! 👍

**Comment by s4cha** [comment]
Hi @yuhua-chen 

This is indeed a very common scenario :)

One solution would be to wrap your call in your own `Promise` , enabling you to catch `ws` errors and then throw your **own errors**.

`.onError` supports everything that conforms to `ErrorType` so in your case you could have your own app errors defined in an enum like So 

``` swift
enum MyError:ErrorType {
    case DefaultError
//...
}
```

``` swift
func getItem() -> Promise<Item> {
    return Promise { resolve, reject in
        ws.get("/item/1234")
            .then(resolve)
            .onError { e in
              // Here you can check the ws error and return you own \o/
              reject(MyError.DefaultError)
        }
    }
}


getItem().then { item in

}.onError { e in
    // Here is your curstom error
}
```

Hope it helps :)

**Comment by yuhua-chen** [comment]
Thanks for reply. 🍺
