### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by lfarah** [s4cha/ws#15]
I'd be cool to also add CocoaPods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by s4cha** [comment]
@lfarah Thanks for the suggestion, It took some time to figure it out since our dependencies didn't have the same names on Carthage and pods, this should be available pretty soon now

**Comment by lfarah** [comment]
Awesome! 🎉

**Comment by s4cha** [comment]
@lfarah  Happy to announce Cocoapods support \o/
