### ISSUE TITLE
Log levels

### ISSUE THREAD

**Issue by maxkonovalov** [s4cha/ws#2]
Hey, great framework, I really enjoy using it :)
Would be nice though to add **logging levels** or at least an ability to temporarily disable the console logs for ws.
Also the same response is printed twice if `Promise` with custom model object is returned, which seems unnecessary.

**Comment by s4cha** [comment]
Hey @maxkonovalov, I'm super happy you enjoy it :) Thanks for the lovely feedback, I am going to look into this and will report back to you when it's solved.
Cheers

**Comment by s4cha** [comment]
@maxkonovalov logging levels are now supported in version 1.1.0. 🎉
`ws.logLevels = .CallsAndResponses`
Values are `None`(default), `Calls` and `CallsAndResponses`
Have a great day!
PS: The double printed response shouldn't happen anymore

**Comment by maxkonovalov** [comment]
@s4cha great! 👏 many thanks)))
