### ISSUE TITLE
Upload App Store Unsupport arm64

### ISSUE THREAD

**Issue by NexusMTO** [s4cha/ws#23]
I use ws 1.1.5 

I can not upgrade to 1.3, because  It stops working because all my application, I prefer to only use this version

Cartfile.resolved

github "Alamofire/Alamofire" "3.2.1"
github "s4cha/Arrow" "0.7.6"
github "stephencelis/SQLite.swift" "0.10.1"
github "s4cha/then" "2.0.1"
github "s4cha/ws" "1.1.5"

I use command carthage update

Carthage/Checkouts/ws/ws/WS.swift:13:8: error: module file was created by a newer version of the compiler: /Carthage/Checkouts/ws/Carthage/Build/iOS/then.framework/Modules/then.swiftmodule/arm64.swiftmodule
A shell task (/usr/bin/xcrun xcodebuild -project //Carthage/Checkouts/ws/ws.xcodeproj -scheme ws -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* BUILD FAILED **

Old projects this version was used 
github "s4cha/then" "1.4.0"

with ws 1.1.5, now automatically change to 
github "s4cha/then" "2.0.1"

why?

**Comment by s4cha** [comment]
@zephiro What Xcode version and swift version are you using?  also do you have Bitcode enabled in your project?

**Comment by s4cha** [comment]
This is indeed and issue, then version wasnt locked in the Cartfile before as we can see here : https://github.com/freshOS/ws/blob/1.1.5/Cartfile

**Comment by s4cha** [comment]
@zephiro any updates ?

**Comment by Unstop-M** [comment]
Hi Sorry my version xcode is 7.3 swift is 2.1, enable bitcode is YES-

I am use file https://github.com/freshOS/ws/blob/1.1.5/Cartfile and carthage update, no problem build. But when select option  product > archive.

Error.

CompileSwift normal arm64 files.

module file was created by a newer version of the compiler: Carthage/Build/iOS/then.framework/Modules/then.swiftmodule/arm64.swiftmodule

**Comment by Unstop-M** [comment]
I try with cocoapods

When run pod install

error

[!] Unable to satisfy the following requirements:

- `ws (= 1.3.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `ws (= 1.3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.



Podfile

target 'App' do
  
  pod 'ws', "1.3.0"
  use_frameworks!



  pod 'IQKeyboardManagerSwift', '4.0.5'
  pod 'SQLite.swift', '~> 0.11.0'

end

**Comment by Unstop-M** [comment]
Finally upgrade to swift version 3.
