### ISSUE TITLE
POST form-urlencoded and form-data support?

### ISSUE THREAD

**Issue by theabhishek2511** [s4cha/ws#28]
can't seem to figure out if these are supported or not at the moment. can ws do these?

**Comment by s4cha** [comment]
Hi @theabhishek2511,

Yes indeed :)
Content-Type: **application/x-www-form-urlencoded** is the default for requests.

For instance 

``` swift
ws.post(“discussion/1234/messages”, params: ["message": "Hello there"])
```

Concerning Content-Type: **multipart/form-data** useful for uploading files, look for the multipart version like so :

``` swift
ws.postMultipart("/upload/avatar", params: ["foo": "bar"], name: "file", data: data, fileName: "photo.jpg", mimeType: "image/jpeg")
```

Hope it helps ;)

**Comment by theabhishek2511** [comment]
Thank you!
