### ISSUE TITLE
ws could support Multipart requests & Form Data Request?

### ISSUE THREAD

**Issue by arden** [s4cha/ws#3]
ws could support Multipart requests & Form Data Request?

**Comment by s4cha** [comment]
Multipart is not supported at the moment but it will be in the future for sure :)

**Comment by s4cha** [comment]
@arden multipart support is in the works on branch "multipart"

You can use it like so 

``` swift
ws.postMultipart("/photos/upload" , params: params, name: "file", data: photo.data, fileName: "photo.jpg", mimeType: "image/jpeg").then { json in

}
```

Enjoy :)

**Comment by florentdouine** [comment]
Hi @s4cha,

i'm trying to upload a photo using your putMultipart functions but i've got some issues.
I would like to PUT a customer with some informations (firstname, lastname, etc...) and add an avatar in the same request.

App crashed when going in this part of code 

``` Swift
//Function sendMultipartRequest            
                for (key,value) in self.params {
                    if let int = value as? Int {
                        let str = "\(int)"
                        if let d = str.dataUsingEncoding(NSUTF8StringEncoding) {
                            formData.appendBodyPart(data: d, name: key)
                        }
                    } else {
                        if let d = value.dataUsingEncoding(NSUTF8StringEncoding) {
                            formData.appendBodyPart(data: d, name: key)
                        }
                    }
                }
```

I don't really understand why you have to send again the params whereas you already send them in the "buildRequest()" function. Can you explain me this part ?

**Comment by iraycd** [comment]
Cannot convert return expression of type 'Promise<JSON>' to return type 'Promise<GroupCreateAPI>' ??

**Comment by s4cha** [comment]
@arden multipart si now support so closing this for now. If you still need Form Data request please open a separate issue :)
@iraycd could you please open a new issue with more details ?
@florentdouine Are you still experiencing the issue with the latest version?
