### ISSUE TITLE
Handle http code

### ISSUE THREAD

**Issue by Nexmind** [s4cha/ws#36]
Hello,

I dont find in the README how to get the HTTP code in case of response. 

Is it possible ? If yes i think this could be nice to add it in the README :-)

**Comment by s4cha** [comment]
Hello @Nexmind 

```swift
ws.get("/users").then {
    // Do something
}.onError { e in
    if let wsError = e as? WSError {
        print(wsError.status)
        print(wsError.status.rawValue) // RawValue for Int status
    }
}
```
You can find the Error enum here ->
https://github.com/freshOS/ws/blob/master/ws/WSError.swift

Hope it helps :)

**Comment by s4cha** [comment]
Just added this to the README, Thanks for bringing that up :)
