### ISSUE TITLE
Carthage frameworks

### ISSUE THREAD

**Issue by maxkonovalov** [s4cha/ws#4]
There are errors when submitting an archive that contains ws framework added via Carthage:

![screen-shot-2](https://cloud.githubusercontent.com/assets/3026460/14583995/eddebb9c-0444-11e6-867a-18206f832b9a.png)

This is caused by `ws.framework` containing its own `Frameworks` folder. I guess, that's because of the "Run Script" build phase included in ws target, which also results in including `then.framework` twice when submitting the build:

![screen-shot-1](https://cloud.githubusercontent.com/assets/3026460/14584018/85c450c0-0445-11e6-89b2-cd75d99e69cc.png)

I worked around the issue by adding a "Run Script" build phase in the host app's target to remove the nested "Frameworks" folder:

```
cd "${SRCROOT}/Carthage/Build/iOS/ws.framework"
if [[ -d "Frameworks" ]]; then
rm -fr Frameworks
fi
```

But it would be great if it could be fixed directly in the framework 😉

**Comment by s4cha** [comment]
@maxkonovalov thanks for the bug report, I tried something at : 9a6c0a646db2de193857876d991a044923cbf8ba
Could you try pointing to this commit in your Cartfile and see if it solved your issue ?
Cheers,

**Comment by s4cha** [comment]
@maxkonovalov latest version 1.1.5 should solve your issue :)
https://github.com/s4cha/ws/releases

**Comment by maxkonovalov** [comment]
@s4cha thanks! It fixed the issue :)
Btw, the dependencies in ws carthage still point to the old 0.7.6 release of Arrow

**Comment by s4cha** [comment]
@maxkonovalov Awesome! thanks a ton for the bug report :) I'm currently updating ws to support multipart and it will ship with the latest Arrow version. Hopefully it'll be ready sometime next week :)
