### ISSUE TITLE
Release 3.1.0 not available in CocoaPods

### ISSUE THREAD

**Issue by gobetti** [s4cha/ws#56]
Hi!

I see that [the last CocoaPods release is 3.0.0](https://cocoapods.org/pods/ws), however the [current podspec](https://github.com/freshOS/ws/blob/master/ws.podspec) says 3.1.0, are we perhaps just missing a push to CocoaPods?

Thanks!

**Comment by s4cha** [comment]
Hi @gobetti I am coming back to the project after quite a bit of absence (We are now at 5.1.1).
I am going to close this for now, don't hesitate to reopen if needed :)
PS: Better late than never, I guess
