### ISSUE TITLE
When will swift5 be supported?

### ISSUE THREAD

**Issue by arden** [s4cha/ws#64]
When I tried to use the ws framework, I found that it relied on Then and Arrow libraries, but neither of them supported swift5. Now that swift5 has been released for so long, I really hope to update it to support swift5 soon. Thanks.

**Comment by WalidDev1** [comment]
same probleme 

> Module compiled with Swift 4.2 cannot be imported by the Swift 5.0.1 compiler: /Users/majMajjanejane/Desktop/StarterProject-master/Carthage/Build/iOS/ws.framework/Modules/ws.swiftmodule/arm64.swiftmodule

>

**Comment by s4cha** [comment]
@arden @WalidDev1 Please excuse the delay, this is coming soon :)

**Comment by s4cha** [comment]
https://github.com/freshOS/ws/releases/tag/5.0.0 🎉 

Closing this for now, feel free to reopen if you encounter an issue with the swift 5 version :)

Thank you so much for your patience 🙏
