### ISSUE TITLE
the JSON parse can as plugins?

### ISSUE THREAD

**Issue by arden** [s4cha/ws#8]
the JSON parse can as plugin? because some times, people hope to use other JSON parser, like JASON, SwiftyJSON,etc.

**Comment by s4cha** [comment]
@arden in the master version, only the `get` can return JSON, which is an issue.
We are going to add JOSN versions for PUT, POST & DELETE so that people can opt out of Arrow if they want to.

Thanks a lot :)

**Comment by s4cha** [comment]
@arden version 1.2 (just released) provides a pure JSON api for the ones who want to opt out form using Arrow :)

Let me know if it solves your issue ;)

**Comment by s4cha** [comment]
@arden can you confirm this is closed?
